### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by LukeTowers** [gcormier/esphome-pressure#1]
Is there a tutorial on how to set this up / install it on a forced air furnace and then integrate it into Home Assistant? I find the concept very compelling, but I'm not exactly sure where to start to actually get this set up on my furnace 😂

**Comment by LukeTowers** [comment]
@gcormier any updates?

**Comment by gcormier** [comment]
> @gcormier any updates?

I've just updated the readme with a setup guide. Take a look and let me know if that proves useful.

**Comment by LukeTowers** [comment]
Thanks! Any idea when it'll be back in stock?

**Comment by gcormier** [comment]
I was hoping to see 2-3 people on the waitlist before putting in a new order. I see you signed up, so maybe I'll put one in soon which means it'd probably be back in stock in March.
