### ISSUE TITLE
Not reading the correct value

### ISSUE THREAD

**Issue by kramttocs** [gcormier/esphome-pressure#5]
Posted on the forum but figure better to do so here. 

Using mine for a radon fan so one port is left open and the other connected to the suction pipe of the fan system.
Online seems like radon fans should be well under 2". With .5" being the most common I see. Prior to ordering, confirmed mine was .8" to be sure it was safely under the 2" limit.

Using the same drilled hold in the suction pipe, my analog u tube shows .8" WC and my digital manometer show .77-.85". Switching the manometer to kpa shows 0.2kPa.

Hooking up the sensor after zeroing it out and leaving one port open is .43 to .45 kPa.
This would be 1.77".
Am I missing something?
That’s pushing the 2" hard and I don’t want to break it but at the same time, it really shouldn’t be that close so not sure what’s going on.

**Comment by gcormier** [comment]
Did you try switching ports? One is marked low pressure the other high. Not sure if they truly have much effect on readings or not.

**Comment by kramttocs** [comment]
Hey. I wondered the same so I did actually. Both read the exact same (so that's good as far as consistency goes :) ). 
I know in your post on the HA forum you mentioned being more concerned with changes from the norm more than what the actual numerical norm is but if you connect/compare it to your manometer, does it read the same?

**Comment by kramttocs** [comment]
I hooked it to my air handler (planning to order another for permanent if we can figure out this out) and still got way higher than my manometer.  Let me know if there is another way to test.

**Comment by gcormier** [comment]
I'll need some time to figure out a way to test, and I'll test a few units. Can you share your YAML here for the sensor section?

**Comment by kramttocs** [comment]
Thanks! If there's a baseline you come up with where I can test also, let me know. The analog u tube was the best I could come up with. 
Here you go:

![image](https://github.com/user-attachments/assets/ffd953c3-9079-41e8-8b77-5edd52ba9dd9)

**Comment by gcormier** [comment]
Can you provide me the laser marking code on the sensor itself? Should be
something like 6899001Dxxxx

**Comment by kramttocs** [comment]
Here you go:
6899001DF441

**Comment by gcormier** [comment]
Thanks. I've tested different markings and gotten consistent results, so I think the laser markings are a data or lot code. I've ordered some T-fittings and more tube to be able to test simultaneous devices and will report back.

I'm gonna leave this issue open until we confirm it was either shipping damage or something else.

**Comment by gcormier** [comment]
I did some testing. `k_value` is supposed to be `8192` for the +/- 0.5kPa sensors. Can you let me know if that helps?

![image](https://github.com/user-attachments/assets/1ab80a44-59cb-4d30-82b7-2b458e4ddc8e)

**Comment by kramttocs** [comment]
Great! It will probably be this evening before I can but the fact that it would be double originally sounds spot on for what I was seeing.

**Comment by kramttocs** [comment]
Looks like we are in business. The readings are halved and much more inline with my manometer. Excellent find!
