### ISSUE TITLE
Feature suggestions: Expose GPIO

### ISSUE THREAD

**Issue by jmtorres** [gcormier/esphome-pressure#6]
A few additional features would make this an amazing All in one Air Handler monitoring device:

1. 1-wire interface to connect DS18B20, DHT22, and other Temperature and/or Humidity sensors.
2. Optocoupled / isolated 24VAC inputs to monitor float switches and call status.
3. Relay outputs to override thermostat.

I had originally planned to use an older [Shelly UNI board](https://kb.shelly.cloud/knowledge-base/shelly-uni) which can handle 24vac power and 2x 24vac inputs. However, it'd be missing the pressure sensor. 

Some inspiration: https://www.youtube.com/watch?v=Hv6urCTRV70

**Comment by gcormier** [comment]
I've got a couple of the foundational pieces already, so perhaps a project for winter 24/25. Relay outputs does not interest me since they must be a dime a dozen from Ali. I wonder if there are any sort of module standard pinouts for these.

**Comment by jmtorres** [comment]
The relay output hasn't been high on my list for this project, but the others are essential in my book. If the a esptemp8c had the differential pressure sensor and some 24vac capable inputs, that would be an ideal device. 

I have a few PMS sensors running on AirGradient and ESPHome. Have you used them within or near an air handler? I'm under the impression that it's not ideal near turbulent air.

**Comment by gcormier** [comment]
I'm not a big fan of the PMS sensors. I've have much better results with the Panasonic GCJA. I have two in my ducts and they work great. Both are designed for industrial equipment monitoring so perhaps that helps?

**Comment by afallows** [comment]
> A few additional features would make this an amazing All in one Air Handler monitoring device:
> 
> 1. 1-wire interface to connect DS18B20, DHT22, and other Temperature and/or Humidity sensors.
> 2. Optocoupled / isolated 24VAC inputs to monitor float switches and call status.
> 3. Relay outputs to override thermostat.
> 
> I had originally planned to use an older [Shelly UNI board](https://kb.shelly.cloud/knowledge-base/shelly-uni) which can handle 24vac power and 2x 24vac inputs. However, it'd be missing the pressure sensor.
> 
> Some inspiration: https://www.youtube.com/watch?v=Hv6urCTRV70

This comment resonates with me as well. A couple 24VAC capable inputs, a couple relay outputs and a couple temperature inputs would make this the perfect smart HVAC device.

**Comment by gcormier** [comment]
I wonder if I could kickstart it or something. Making the design is trivial, it's more a question of having a bunch of boards sitting around that nobody is buying. I think I have old designs that I never even made with those exact requirements.

I'm not sure about relay outputs though - those are pretty cheap commodity items on the usual suspects... it might add extra cost, but I guess it's the usual Lada/Civic/BMW conundrum and I'm often aiming for the last option when designing these things as I like a neat and well designed option instead of things that look like bombs around the house :)

**Comment by jmtorres** [comment]
As you can see on the HA subreddit, there is some interest. What is the smallest run that would be feasible?

This is my current rigged up solution with the Shelly UNI. This handles the additional features I mentioned, excluding the pressure differential sensor. It'd definitely not pretty or ideal. Although it does have 24VAC capable isolated outputs, the current rating doesn't seem to be enough for an HVAC contactor.

![IMG_5092](https://github.com/user-attachments/assets/0cd0bddf-2afb-4b02-b01b-180279fa31bb)
![IMG_5093](https://github.com/user-attachments/assets/641d88a1-1783-489d-842b-4abde85c1756)

**Comment by gcormier** [comment]
Relays add a few $ for parts, fees and bigger power section to power said relays. (Solid state relays wouldn't be ideal in this application - they can sometimes leak a tiny current, which is enough for something digital on the other end to interpret "on")

Optos another few $ in parts and fees. Bigger PCB to fit all of those, and pluggable headers. Switch the ESP32 from a C3-MINI to one with more GPIO's to control all those.

For the small runs I'm doing it might increase the cost about 15$ per? I'd have to do the design to find out.

**Comment by afallows** [comment]
Just ordered a new style board from you but put in the wrong address by one digit. 9131 should be 9135. Trying to figure out how to fix it

**Comment by rewardone** [comment]
I had this on my waitlist. Cool to see a breakout for temperature probes. This was the next thing I was looking at monitoring after pressure. With the breakouts, I assume I should be able to add two probes like these [adafruit ones](https://www.digikey.com/en/products/detail/adafruit-industries-llc/381/5875807?s=N4IgTCBcDaICIGUCMAOAQmADAAjgSwHM8AXAQwBtsAVAUwFsAHGgJ1OIFdmbsEaA7AM4B7ZiAC6AXyA) for differential temperature? 

Adding additional relays could be cool, but I don't know how large the market is. A $150-$200 price is battling a thermostat. 
As a monitoring and accessory control device, it would be interesting. I ask HVAC contractors about powering my 3 accessories from a single source and they think I'm crazy (humidifier, dehumidifier, ERV/fan).

**Comment by gcormier** [comment]
Yup you can use those sensors, check out https://github.com/gcormier/esptemp8c for more info. Didn't hardware but same process for 1 wire

**Comment by gcormier** [comment]
Design now breaks out a few GPIOs.

**Comment by gcormier** [comment]
Added a new discussion for expanding capabilities as I'm getting an increased amount of interest

https://github.com/gcormier/esphome-pressure/discussions/22
